process.env.GITHUB_CLIENT_ID ='test-client-id'
process.env.GITHUB_CLIENT_SECRET ='test-client-secret'
process.env.REDIS_SERVICE_PORT='6377'
process.env.REDIS_SERVICE_IP='10.1.1.20'
process.env.NODE_ENV='testing'