name: Build
on:
  push:
    branches:
      - master
jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
  elm_analyse:
    needs: build_packages
    runs-on: ubuntu-latest
    steps:
        - uses: borales/actions-yarn@v2.0.0
          with:
            cmd: elm-analyse
