name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Build packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install --ignore-engines

    - name: elm-analyse
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: elm-analyse
