name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - name: Install JS dependencies
        # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run ts unit tests
        run: yarn ts:test

      - name: elm-analyse
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: elm-analyse
